tool_tier: minecraft:diamond
tool_category: minecraft:axe
break_speed: 1.5
attack_damage: 6.5
attack_speed: 2.1
can_sweep_attack: true
can_break_blocks_in_creative: false
max_durability:  781
item_damage_on_attack_entity: 1
item_damage_on_break_block: 2
enchantment_value: 10
enchantment_categories: ["weapon", "breakable"]