tool_tier: minecraft:diamond
tool_category: minecraft:shovel
break_speed: 10
attack_damage: 5.5
attack_speed: 1
can_sweep_attack: false
can_break_blocks_in_creative: true
max_durability:  781
item_damage_on_attack_entity: 2
item_damage_on_break_block: 1
enchantment_value: 10
enchantment_categories: ["digger", "breakable"]