tool_tier: minecraft:diamond
tool_category: minecraft:hoe
break_speed: 20
attack_damage: 1.5
attack_speed: 4
can_sweep_attack: false
can_break_blocks_in_creative: true
max_durability:  781
item_damage_on_attack_entity: 2
item_damage_on_break_block: 1
enchantment_value: 10
enchantment_categories: ["digger", "breakable"]